In [1]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1')

In [2]:
epsilon = 0.99
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.01

total_episodes = 10000
max_steps = 100

lr_rate = 0.7	# 0.81
gamma = 0.99	# 0.96

qtable = np.zeros((env.observation_space.n, env.action_space.n))

In [3]:
def choose_action(state):
	action=0
	if np.random.uniform(0, 1) < epsilon:
		action = env.action_space.sample()
	else:
		action = np.argmax(qtable[state, :])
	return action

def learn(state, state2, reward, action, action2):
	predict = qtable[state, action]
	target = reward + gamma * qtable[state2, action2]
	qtable[state, action] = qtable[state, action] + lr_rate * (target - predict)

In [4]:
rewards=0

for episode in range(total_episodes):
	t = 0
	state = env.reset()
	action = choose_action(state)
    
	while t < max_steps:

		state2, reward, done, info = env.step(action)

		action2 = choose_action(state2)

		learn(state, state2, reward, action, action2)

		state = state2
		action = action2

		t += 1
		rewards+=1

		if done:
			epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
			#print(epsilon)
			break

print(qtable)

[[4.59258118e-01 1.36068824e-01 1.41521259e-01 2.42443945e-01]
 [3.07050325e-02 5.37284593e-02 1.02747002e-02 2.49515175e-01]
 [5.20784551e-02 8.40248003e-02 4.57110523e-02 1.76227205e-01]
 [1.32587931e-02 4.82909404e-02 1.74200156e-03 1.51123923e-01]
 [6.49463775e-01 1.12256548e-01 1.45987249e-01 9.28390625e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.58797598e-05 4.36293518e-03 4.74238106e-03 6.72799915e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.11208328e-02 6.58787439e-03 5.74352586e-02 8.37148397e-01]
 [1.32617516e-02 7.82610801e-01 1.59359437e-04 5.32592244e-02]
 [9.15869064e-01 1.32356173e-02 2.36028880e-03 8.23698181e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.99141883e-02 6.24475765e-02 9.79828504e-01 1.83958462e-01]
 [3.22898839e-01 9.99832209e-01 4.26074763e-01 4.77120453e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [5]:
env.reset()

max_iteration = 100
victory = 0
steps = []

for episode in range(max_iteration):
    state = env.reset()
    step = 0
    done = False

    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            # env.render()
            if reward == 1:
                victory += 1
                steps.append(step)
            break
        state = new_state
        
env.close()

In [6]:
print("Pourcentage de réussite en mode QLearning : ", victory / max_iteration * 100, "%")
print("Nombre moyen de pas pour arriver au but : ",np.mean(steps))
print("Nombre median de pas pour arriver au but : ",np.median(steps))

Pourcentage de réussite en mode QLearning :  77.0 %
Nombre moyen de pas pour arriver au but :  38.87012987012987
Nombre median de pas pour arriver au but :  39.0
