In [26]:
import numpy as np
import gym
import random
env = gym.make("FrozenLake-v1")

In [27]:
action_size = env.action_space.n
state_size = env.observation_space.n

qtable = np.zeros((state_size, action_size))
# print(qtable)

In [28]:
total_episodes = 10000
learning_rate = 0.7          
max_steps = 99             
gamma = 0.95                


epsilon = 1.0                 
max_epsilon = 1.0             
min_epsilon = 0.01           
decay_rate = 0.005       

rewards = []
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        state = new_state
        
        if done == True: 
            break
 
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)
    

print ("Score: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score: 0.4829
[[2.53037622e-01 4.96724060e-02 1.21721316e-01 1.25916845e-01]
 [2.38514974e-02 8.54606885e-03 3.64272004e-03 1.44463196e-01]
 [3.23364159e-02 4.04902079e-02 1.77472823e-02 5.70839191e-02]
 [1.40069736e-02 1.09227895e-03 1.66607185e-03 4.84574131e-02]
 [3.34958018e-01 1.24716014e-02 8.02324793e-02 5.70959645e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.81239968e-01 2.59967707e-05 1.42174426e-04 1.15565720e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.39756754e-02 4.38644773e-02 7.72869982e-02 4.48838242e-01]
 [1.22755148e-01 6.08100460e-01 1.14649344e-01 1.01373028e-01]
 [4.73297647e-01 5.28741022e-03 5.78873622e-04 1.92040819e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.23584038e-01 1.46608843e-01 8.60003344e-01 4.90049265e-02]
 [4.96492570e-01 9.95563454e-01 2.71376788e-01 6.72824240e-01]
 [0.00000000e+00 0.00000000e+00 0.0000000

In [29]:
env.reset()

max_iteration = 100
victory = 0
steps = []

for episode in range(max_iteration):
    state = env.reset()
    step = 0
    done = False

    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            # env.render()
            if reward == 1:
                victory += 1
                steps.append(step)
            break
        state = new_state
        
env.close()

In [30]:
print("Pourcentage de réussite en mode QLearning : ", victory / max_iteration * 100, "%")
print("Nombre moyen de pas pour arriver au but : ",np.mean(steps))
print("Nombre median de pas pour arriver au but : ",np.median(steps))

Pourcentage de réussite en mode QLearning :  84.0 %
Nombre moyen de pas pour arriver au but :  36.69047619047619
Nombre median de pas pour arriver au but :  29.5
